Iter13
itaraxa/effectivepancake pull request #15
Opened 2024-11-13 21:06 UTC by itaraxa

2024-11-17 18:43 UTC, bulbetski requested changes
В целом код нормальный, но есть пара мест, которые требуют доработок, по типу приведения типов и обработки ошибок

2024-11-17 18:43 UTC, bulbetski commented on cmd/agent/main.go
>  	}
В main функции можно сразу завершать программу через log.Fatal. Использование метода fmt.Println не принято в продакш-реди приложениях

2024-11-17 18:43 UTC, bulbetski commented on cmd/server/main.go
>  			sa.logger.Error("metric data hasn't been saved to the file", "error", err.Error(), "filename", sa.config.FileStoragePath)
Два лога в одном err != nil условии. Инфо надо вынести отсюда

2024-11-17 18:43 UTC, bulbetski commented on cmd/server/main.go
> +		ctx3s, cancel3s := context.WithTimeout(ctx, 3*time.Second)
можно просто назвать ctxWithTimeout

2024-11-17 18:43 UTC, bulbetski commented on cmd/server/main.go
> +		return
Стоит завершать через log.Fatal

2024-11-17 18:43 UTC, bulbetski commented on cmd/server/main.go
> +		app.Run()
Это должно происходить вне зависимости от выбора хранилища. То есть от наличия дсна зависит только то, какой репозиторий мы используем

2024-11-17 18:43 UTC, bulbetski commented on internal/config/agent.go
> +		Batch:          true,
мб это как-то конфигурировать?

2024-11-17 18:43 UTC, bulbetski commented on internal/handlers/dbhandlers.go
> +			return
Проверка метода HTTP-запроса выглядит не очень гибко. Если в будущем появится необходимость поддерживать другие методы, потребуется доработка. Сам маршрутизатор по сути обрабатывает запрос и если в маршрутизаторе метод записан в гет, то только гет и будет.

2024-11-17 18:43 UTC, bulbetski commented on internal/handlers/dbhandlers.go
> +		w.Header().Set("Content-Type", "text/html")
Мы вообще ничего не пишем в ответ, но тем не менее хэдер какой-то ставим. Либо не нужен хэдер, либо нужно записать ответ

2024-11-17 18:43 UTC, bulbetski commented on internal/handlers/handlers.go
>  			l.Error("cannot write HTML to response body")
Понимаю, что в этом месте по сути функция завершается, но стоит сделать аналогично первой ошибке. запись хттп ошибку в ответ и сделать return

2024-11-17 18:43 UTC, bulbetski commented on internal/handlers/handlers.go
> +func GetMetrica(ctx context.Context, s metricGetter, l logger) http.HandlerFunc {
Логирование происходит в начале функции, но значения из `chi.URLParam` извлекаются многократно. Можго вынесенти параметры в переменные перед логированием, чтобы избежать повторного извлечения.
		metricType := chi.URLParam(req, "type")
		metricName := chi.URLParam(req, "name")

2024-11-17 18:43 UTC, bulbetski commented on internal/handlers/handlers.go
>  			res = fmt.Sprint(v.(int64))
Преобразования типов могут приводить к панике, надо проверять на ok еще.

Также можно вообще не создавать переменную res, а сразу писать в ответ w.Write(что-то там)

2024-11-17 18:43 UTC, bulbetski commented on internal/handlers/handlers.go
>  			jm.Delta = &t
преобразование типов может привести к панике

2024-11-17 18:43 UTC, bulbetski commented on internal/handlers/handlers.go
> +		_, err := buf.ReadFrom(req.Body)
если нет тела запроса, это вызовет панику, надо првоерить на нил

2024-11-17 18:43 UTC, bulbetski commented on internal/handlers/handlers.go
> +		w.Header().Set("Content-Type", "applicttion/json")
опечатка

2024-11-17 18:43 UTC, bulbetski commented on internal/repositories/memstorage/memstorage.go
> +		m.Gauge[metric.MetricName] = *metric.MetricValue
MetricValue может быть nil, что вызовет панику

2024-11-17 18:43 UTC, bulbetski commented on internal/repositories/memstorage/memstorage.go
> +			m.Counter[metric.MetricName] = *metric.MetricDelta
MetricDelta может быть nil, что вызовет панику

2024-11-17 18:43 UTC, bulbetski commented on internal/repositories/memstorage/memstorage.go
> +	return nil
Можно проверить, инициализирована ли мапа, но можно этого и не делать

2024-11-17 18:43 UTC, bulbetski commented on internal/repositories/memstorage/memstorage_test.go
> +			if err := m.UpdateGauge(context.TODO(), tt.args.metricName, tt.args.value); (err != nil) != tt.wantErr {
использование context.TODO() не лучшая практика. Стоит понять, какой контекст тут лучше использовать

2024-11-17 18:43 UTC, bulbetski commented on internal/repositories/postgres/migration.go
> +		content, _ := migrationFiles.ReadFile("migrations/" + file.Name())
не обрабатываем ошибку

2024-11-17 18:43 UTC, bulbetski commented on internal/repositories/postgres/postgres.go
> +		return &PostgresRepository{}, err
тут надо возвращать nil ошибку

2024-11-17 18:43 UTC, bulbetski commented on internal/repositories/postgres/postgres.go
> +		return &PostgresRepository{}, fmt.Errorf("cannot create tables in database storage: %w", err)
аналогично, тут надо возвращать nil ошибку

2024-11-17 18:43 UTC, bulbetski commented on internal/repositories/postgres/postgres.go
> +		fmt.Println(err.Error())
вместо fmt.Println лучше обычное логирование

2024-11-17 18:43 UTC, bulbetski commented on internal/repositories/postgres/postgres.go
> +	}()
этот код повторяется, можно вынести в отдельный метод

2024-11-17 18:43 UTC, bulbetski commented on internal/repositories/postgres/postgres.go
> +		if err == sql.ErrNoRows {
Лучше проверять через errors.Is

2024-11-17 18:43 UTC, bulbetski commented on internal/repositories/postgres/postgres.go
> +			if err == sql.ErrNoRows {
лучше проверять через errors.Is

2024-11-17 18:43 UTC, bulbetski commented on internal/repositories/postgres/postgres.go
> +		fmt.Printf("error getting metrics from postgres storage: %v", err.Error())
лучше логировать через logger

2024-11-17 18:43 UTC, bulbetski commented on internal/repositories/postgres/postgres.go
> +		fmt.Printf("error getting metrics from postgres storage: %v", err.Error())
лучше логировать через logger

2024-11-17 18:43 UTC, bulbetski commented on internal/services/agent.go
> +	jsonDataReq, err := json.Marshal(ms.GetData())
Нет проверки на пустой `ms.GetData()`. Если метрики отсутствуют, создается пустой JSON-запрос. Это может привести к ошибкам на сервере.

2024-11-17 18:43 UTC, bulbetski commented on internal/services/agent.go
> +	req, err := http.NewRequest(`POST`, fmt.Sprintf("http://%s/updates/", serverURL), bytes.NewBuffer(jsonDataReq))
Если `serverURL` уже содержит протокол, это может привести к двойному `http://`. Так что лучше это указать где-нибудь при иниицализации

2024-11-17 18:43 UTC, bulbetski commented on internal/services/agent.go
> +	jsonDataReq, err := json.Marshal(ms.GetData())
Проверка на пустой ms.GetData()

2024-11-17 18:43 UTC, bulbetski commented on internal/services/agent.go
> +		l.Error("cannot compress data", "error", err.Error())
нет return'a

2024-11-17 18:43 UTC, bulbetski commented on internal/services/agent.go
> +func retryDo(l logger, client *http.Client, req *http.Request) (*http.Response, error) {
Код явно повторяет один и тот же блок с небольшими изменениями (номер попытки и таймаут). Это ухудшает читаемость и поддержку. Стоит подумать, как избавиться от дублирования

2024-11-17 18:43 UTC, bulbetski commented on internal/services/server.go
> +	blob["metrics"], _ = mg.GetAllMetrics(ctx)
Не обрабатываем ошибку

2024-11-17 18:43 UTC, bulbetski commented on internal/services/utility.go
> +	fmt.Println(s.String(context.TODO()))
Точно ли тут нужны принты через fmt

2024-11-19 17:36 UTC, itaraxa commented on internal/config/agent.go
> +		Batch:          true,
В ТЗ таких требований не было, я ввел флаг для проверки работы агента в старых режимах - кроме как размера батча ничего в голову не приходит

2024-11-19 20:27 UTC, itaraxa commented on internal/services/agent.go
> +	req, err := http.NewRequest(`POST`, fmt.Sprintf("http://%s/updates/", serverURL), bytes.NewBuffer(jsonDataReq))
Думаю вынести эту проверку в функцию валидации пакета config

2024-11-20 22:18 UTC, bulbetski reviewed
Ну, большинство комментов не исправлено. Надо поправлять, особенно важный с функцией retryDo

2024-11-20 22:18 UTC, bulbetski commented on cmd/agent/main.go
> +		return
пропустил log.Fatal

2024-11-20 22:18 UTC, bulbetski commented on cmd/server/main.go
> +			_ = sa.storage.Close()
Можно залогировать ошибку. Кароч всегда какая-то обработка должна быть

2024-11-20 22:18 UTC, bulbetski commented on cmd/server/main.go
> +		return
log.Fatal

2024-11-20 22:18 UTC, bulbetski commented on internal/handlers/handlers.go
> +				l.Error("type assertion -> float64", "value", value)
не надо ли нам завершить выполнение функции в этом случае?

2024-11-20 22:18 UTC, bulbetski commented on internal/handlers/handlers.go
>  			resp.Delta = &c
а зачем это делать для каунтера? ну и опять же может быть паника

2024-11-20 22:18 UTC, bulbetski commented on internal/handlers/handlers.go
> +				l.Error("type assertion -> int64", "value", value)
не надо ли нам завершить выполнение функции в этом случае?

2024-11-20 22:18 UTC, bulbetski commented on internal/handlers/handlers.go
>  		body, _ := json.Marshal(resp)
пропущена обработка ошибки

2024-11-20 22:18 UTC, bulbetski commented on internal/services/agent.go
> +	req, err := http.NewRequest(`POST`, fmt.Sprintf("http://%s/updates/", serverURL), bytes.NewBuffer(jsonDataReq))
достаточно быть увереным, что оно где-то установлено. Желательно при инициализации клиента. В месте вызова уже об этом думать не надо. 
Либо сделать хелпер для создания запросов и в нем уже делать валидацию

2024-11-20 22:18 UTC, bulbetski commented on internal/services/server_test.go
> +// func TestUpdateMetrica(t *testing.T) {
Оно нам надо, раз оно закоменчено?

2024-11-21 06:09 UTC, itaraxa commented on cmd/agent/main.go
> +		return
Я не считаю что в этом случае нужен log.Fatal. Пользователь указал ключ для того, что бы приложение только вывело версию. Приложение выводит версию и завершает работу

2024-11-21 06:34 UTC, itaraxa commented on cmd/server/main.go
> +			_ = sa.storage.Close()
+

2024-11-21 06:44 UTC, itaraxa commented on cmd/server/main.go
> +		return
Аналогично с таим же блоком в прложении агента. Считаю что это штатное поведение, и оно не должно возвращать ошибку

2024-11-21 07:39 UTC, itaraxa commented on internal/handlers/handlers.go
>  			resp.Delta = &c
Забыл удалить

2024-11-21 07:46 UTC, itaraxa commented on internal/handlers/handlers.go
>  		body, _ := json.Marshal(resp)
добавлена обработка ошибки

2024-11-21 07:51 UTC, itaraxa commented on internal/handlers/handlers.go
> +		_, err := buf.ReadFrom(req.Body)
Добавил проверку

2024-11-21 07:51 UTC, itaraxa commented on internal/handlers/handlers.go
> +		w.Header().Set("Content-Type", "applicttion/json")
исправил

2024-11-21 08:33 UTC, itaraxa commented on internal/repositories/memstorage/memstorage.go
> +		m.Gauge[metric.MetricName] = *metric.MetricValue
Добавил проверку и переход к следующей итерации цикла

2024-11-21 08:36 UTC, itaraxa commented on internal/repositories/postgres/migration.go
> +		content, _ := migrationFiles.ReadFile("migrations/" + file.Name())
Добавил проверку возвращаемой ошибки

2024-11-21 08:57 UTC, itaraxa commented on internal/handlers/handlers.go
> +				l.Error("type assertion -> float64", "value", value)
Надо, добавил return

2024-11-21 08:57 UTC, itaraxa commented on internal/handlers/handlers.go
> +				l.Error("type assertion -> int64", "value", value)
Надо, добавли return

2024-11-21 09:07 UTC, itaraxa commented on internal/services/utility.go
> +	fmt.Println(s.String(context.TODO()))
Эти функции использовались для отладки, переделал их на возврат строки

2024-11-21 10:58 UTC, itaraxa commented on internal/services/agent.go
> +func retryDo(l logger, client *http.Client, req *http.Request) (*http.Response, error) {
Реализовал по аналогии с ретраем запроса к базе данных - через функцию-обертку

2024-11-21 13:44 UTC, itaraxa commented on internal/services/agent.go
> +	req, err := http.NewRequest(`POST`, fmt.Sprintf("http://%s/updates/", serverURL), bytes.NewBuffer(jsonDataReq))
добавил функцию createUrl

2024-11-21 13:48 UTC, bulbetski commented on cmd/agent/main.go
> +		return
да, ты прав, я фигню написал

2024-11-25 09:36 UTC, bulbetski approved these changes
Всё супер исправил. Код хороший

2024-11-25 18:32 UTC, merged