Iter5
itaraxa/effectivepancake pull request #7
Opened 2024-10-05 13:09 UTC by itaraxa

## Added:
- os environment variables support for Server and Agent apps

2024-10-07 14:57 UTC, rktkov requested changes

2024-10-07 14:57 UTC, rktkov commented on cmd/agent/doc2.go
> +// Задание по треку «Сервис сбора метрик и алертинга»
Стоит поместить эти файлы в папку - docs

2024-10-07 14:57 UTC, rktkov commented on cmd/agent/main.go
> +	config     *struct {
Лучше сделать не анонимную структуру в отдельном пакете config, туда же можно вынести чтение флагов.

2024-10-07 14:57 UTC, rktkov commented on cmd/agent/main.go
> +		for {
Как произойдет выход из цикла?

2024-10-07 14:57 UTC, rktkov commented on cmd/agent/main.go
> +		for {
Тот же вопрос - Как произойдет выход из цикла?

Я бы подумал, как вынести логику еще на один уровень, т.е. упростить метод Run

2024-10-07 14:57 UTC, rktkov commented on cmd/server/main.go
> +	"github.com/itaraxa/effectivepancake/internal/handlers"
import

Возьмите в привычку сортировать импортируемые пакеты следующим образом:
1. пакеты стандартной библиотеки
2. внешние установленные пакеты
3. внутренние пакеты проекта

Для того, чтобы разные автоматические инструменты их не пересортировывали, разделяйте блоки пустой строкой.

см. комментарий про порядок импорта
https://stackoverflow.com/questions/24790175/when-is-the-init-function-run

2024-10-07 14:57 UTC, rktkov commented on internal/services/utility_service.go
> +package services
Раз пакет уже называется services, то стоит переименовать файл в utility.go

2024-10-07 14:57 UTC, rktkov commented on internal/services/interfaces.go
> +package services
Перенести объявление интерфейсов в пакеты или файлы, где они используются.

2024-10-07 14:57 UTC, rktkov commented on internal/models/metrica.go
> +type Metrica struct {
Может Metric?

2024-10-13 15:46 UTC, itaraxa commented on cmd/agent/main.go
> +	config     *struct {
Принято. Оформил пакет /internal/config

2024-10-13 15:48 UTC, itaraxa commented on cmd/agent/main.go
> +		for {
Добавил отправку сигнала о нажатии Ctrl+C в цикл. При получении сигнала делается break

2024-10-13 15:48 UTC, itaraxa commented on cmd/agent/main.go
> +		for {
Выход из цикла реализован аналогично с предыдущим.
Сбор и отправка метрик вынесены в отдельные функции в пакете /internal/services

2024-10-13 15:49 UTC, itaraxa commented on cmd/server/main.go
> +	"github.com/itaraxa/effectivepancake/internal/handlers"
Принято

2024-10-13 15:49 UTC, itaraxa commented on internal/services/utility_service.go
> +package services
Принято

2024-10-13 15:49 UTC, itaraxa commented on internal/services/interfaces.go
> +package services
Принято

2024-10-13 15:49 UTC, itaraxa commented on internal/models/metrica.go
> +type Metrica struct {
Принято

2024-10-14 11:13 UTC, rktkov approved these changes

2024-10-14 13:38 UTC, merged